<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="L3701100373" failures="0" tests="5" name="com.adasarca.imagedemo.controller.AuthenticationControllerTest" time="0.198" errors="0" timestamp="2022-08-17T14:40:19 EEST" skipped="0">
  <testcase classname="com.adasarca.imagedemo.controller.AuthenticationControllerTest" name="testSignup" time="0.010"/>
  <system-out/>
  <testcase classname="com.adasarca.imagedemo.controller.AuthenticationControllerTest" name="testSignup_DatabaseException" time="0.013"/>
  <system-out/>
  <testcase classname="com.adasarca.imagedemo.controller.AuthenticationControllerTest" name="testAuthenticate_ValidationException" time="0.017"/>
  <system-out/>
  <testcase classname="com.adasarca.imagedemo.controller.AuthenticationControllerTest" name="testAuthenticate" time="0.149"/>
  <system-out/>
  <testcase classname="com.adasarca.imagedemo.controller.AuthenticationControllerTest" name="testSignup_ValidationException" time="0.009"/>
  <system-out/>
</testsuite> <!-- com.adasarca.imagedemo.controller.AuthenticationControllerTest -->
